name: 'hubspot'
version: '0.3.1'
config-version: 2
require-dbt-version: [">=0.18.0", "<0.20.0"]

vars:

  # Marketing
  hubspot_marketing_enabled: true                        # Disables all marketing models
  hubspot_contact_enabled: true                          # Disables the contact models
  hubspot_contact_list_enabled:  true                    # Disables contact list models
  hubspot_contact_list_member_enabled: true              # Disables contact list member models
  hubspot_contact_property_enabled: true                 # Disables the contact property models
  hubspot_email_event_enabled: true                      # Disables all email_event models and functionality
  hubspot_email_event_bounce_enabled: true
  hubspot_email_event_click_enabled: true
  hubspot_email_event_deferred_enabled: true
  hubspot_email_event_delivered_enabled: true
  hubspot_email_event_dropped_enabled: true
  hubspot_email_event_forward_enabled: false
  hubspot_email_event_opens_enabled: true
  hubspot_email_event_print_enabled: false
  hubspot_email_event_sent_enabled: true
  hubspot_email_event_spam_report_enabled: false
  hubspot_email_event_status_change_enabled: false

  # Sales

  hubspot_sales_enabled: true                            # Disables all sales models
  hubspot_company_enabled: true
  hubspot_deal_enabled: false
  hubspot_engagement_enabled: false                       # Disables all engagement models and functionality
  hubspot_engagement_contact_enabled: false
  hubspot_engagement_company_enabled: false
  hubspot_engagement_deal_enabled: false
  hubspot_engagement_calls_enabled: false
  hubspot_engagement_emails_enabled: false
  hubspot_engagement_meetings_enabled: false
  hubspot_engagement_notes_enabled: false
  hubspot_engagement_tasks_enabled: false

  hubspot:
    contact: "{{ ref('stg_hubspot__contact') }}"
    contact_list: "{{ ref('stg_hubspot__contact_list') }}"
    contact_list_member: "{{ ref('stg_hubspot__contact_list_member') }}"
    contact_property_history: "{{ ref('stg_hubspot__contact_property_history') }}"

    company: "{{ ref('stg_hubspot__company') }}"
    company_property_history: "{{ ref('stg_hubspot__company_property_history') }}"

    deal: "{{ ref('stg_hubspot__deal') }}"
    deal_company: "{{ ref('stg_hubspot__deal_company') }}"
    deal_pipeline: "{{ ref('stg_hubspot__deal_pipeline') }}"
    deal_pipeline_stage: "{{ ref('stg_hubspot__deal_pipeline_stage') }}"
    deal_property_history: "{{ ref('stg_hubspot__deal_property_history') }}"

    owner: "{{ ref('stg_hubspot__owner') }}"

    email_event_bounce: "{{ ref('stg_hubspot__email_event_bounce') }}"
    email_event_click: "{{ ref('stg_hubspot__email_event_click') }}"
    email_event_deferred: "{{ ref('stg_hubspot__email_event_deferred') }}"
    email_event_delivered: "{{ ref('stg_hubspot__email_event_delivered') }}"
    email_event_dropped: "{{ ref('stg_hubspot__email_event_dropped') }}"
    email_event_forward: "{{ ref('stg_hubspot__email_event_forward') }}"
    email_event_open: "{{ ref('stg_hubspot__email_event_open') }}"
    email_event_print: "{{ ref('stg_hubspot__email_event_print') }}"
    email_event_sent: "{{ ref('stg_hubspot__email_event_sent') }}"
    email_event_spam_report: "{{ ref('stg_hubspot__email_event_spam_report') }}"
    email_event_status_change: "{{ ref('stg_hubspot__email_event_status_change') }}"
    email_event: "{{ ref('stg_hubspot__email_event') }}"

    engagement: "{{ ref('stg_hubspot__engagement') }}"
    engagement_call: "{{ ref('stg_hubspot__engagement_call') }}"
    engagement_company: "{{ ref('stg_hubspot__engagement_company') }}"
    engagement_contact: "{{ ref('stg_hubspot__engagement_contact') }}"
    engagement_deal: "{{ ref('stg_hubspot__engagement_deal') }}"
    engagement_email_cc: "{{ ref('stg_hubspot__engagement_email_cc') }}"
    engagement_email_to: "{{ ref('stg_hubspot__engagement_email_to') }}"
    engagement_email: "{{ ref('stg_hubspot__engagement_email') }}"
    engagement_meeting: "{{ ref('stg_hubspot__engagement_meeting') }}"
    engagement_note: "{{ ref('stg_hubspot__engagement_note') }}"
    engagement_task: "{{ ref('stg_hubspot__engagement_task') }}"

    email_metrics:
      - bounces
      - clicks
      - deferrals
      - deliveries
      - drops
      - forwards
      - opens
      - prints
      - spam_reports

models:
  hubspot:
    +materialized: table
    +schema: hubspot
    marketing:
      intermediate:
        +materialized: ephemeral